name: ChatFAQ
main: dev.oribuin.chatfaq.ChatFAQPlugin
version: '@version@'
api-version: '1.19'
author: Oribuin
description: reduce chat spam with repetitive questions from new players
permissions:
  chatfaq.bypass:
    description: Bypasses the check for all faq questions
    default: false